### ISSUE TITLE
ANYONE support

### ISSUE THREAD

**Issue by PeteLawrence** [PeteLawrence/homebridge-people#10]
Add in a ANYONE sensor that reports if anyone is in.

**Comment by luc-ass** [comment]
Does this mean: 
1) Pete, Luke, Angela, Dave → one of those is home or
2) any! (mobile IP) is pingable
?

**Comment by PeteLawrence** [comment]
1 - If any of the defined devices is pingable it will return true.

Released in v.0.3.3
