### ISSUE TITLE
v0.3.3 everyone away

### ISSUE THREAD

**Issue by luc-ass** [PeteLawrence/homebridge-people#11]
Hey there, just updated to v0.3.3. After the update all people are away. Noticeable the "ping" process is not as visible in "top" as before. Any ideas? Restart didn't help...

**Comment by mrbeach69** [comment]
I got the problem... Not working anymore

**Comment by luc-ass** [comment]
Check if you have changed "ip" to "target". I have not checked if it works but it seems like an cause.

**Comment by PeteLawrence** [comment]
Good spot, there was a bug in the code that handles the old 'ip' config key.  I've just published 0.3.4 to fix this.
