### ISSUE TITLE
Not Detecting People

### ISSUE THREAD

**Issue by erfinb** [PeteLawrence/homebridge-people#14]
Have tried using IP and Device name and am unable to detect any users.... :-(

**Comment by PeteLawrence** [comment]
If you are running homebridge on a raspberry pi as it's own user see the note that I've just added to the bottom of the README.md

**Comment by robertvorthman** [comment]
Pete, thank you.  Running `sudo chmod u+s /bin/ping` on my Raspberry Pi fixed this issue for me.

**Comment by erfinb** [comment]
I'm running OS X but will take a look :)
