### ISSUE TITLE
HomeKit client apps see no names, just "Occupancy Detected" or "Occupancy Sensor"

### ISSUE THREAD

**Issue by JonSilver** [PeteLawrence/homebridge-people#15]
Thanks for your great work so far Pete! Would it be possible for HomeKit client apps to see something more useful for each tracked individual? At the moment it's practically unusable for events in Elgato Eve or MyTouchHome.

Jon

**Comment by JonSilver** [comment]
Hmmm looking further into it, is this a limitation of Homebridge itself, or of how the whole occupancy thing was conceived in HomeKit, or of the client apps? Upon inspection of the code, homebridge-people looks like it's already doing all it can to properly identify each person.

**Comment by PeteLawrence** [comment]
Using the Elgato Eve app the names show when listing 'Occupancy Detected' types, but not when listing devices in a room or setting up triggers for example.  I believe the order is the same throughout the app, so by seeing which position the device you're interested in appears in the Occupancy Detected list, you should be able to setup a trigger based on that device.

It would be handy if client apps did display the subtype more visibly, or I could rework the plugin to expose each monitored device as its own Accessory, rathern than a Service within a single Accessory.

**Comment by luc-ass** [comment]
I would also like it this way as it reflects different persons/devices. Let me know if I can help you with it...

**Comment by JonSilver** [comment]
Is the problem that HomeKit occupancy was conceived as a sensor per room to determine presence, rather than presence of someone anywhere in a home? A bit short-sighted perhaps. There may be no way around it, except waiting for Apple to change HomeKit.

**Comment by amitgandhinz** [comment]
Its the same issue in the iDevices app, where it only shows "Current Occupancy" as the heading, but does not display the people's names.  I do see the names of the people in other homekit apps though.

**Comment by JonSilver** [comment]
The latest Elgato Eve is brilliant, and clearly uses the names specified in the Homebridge config everywhere including rules... So no action needed! :) Case closed.
