### ISSUE TITLE
Triggers not working

### ISSUE THREAD

**Issue by robertvorthman** [PeteLawrence/homebridge-people#16]
I can't seem to get a trigger to fire based on an occupancy sensor state.  Where is the "seen.db.json" so I can check if my device is being pinged?  Thanks.

**Comment by PeteLawrence** [comment]
The version on npm doesn't support triggers. I've added in support for triggers over the weekend, but I'm doing a bit of testing before pushing to npm. So you can either grab the latest version from GitHub, or wait a couple of days until I push it to npm.

**Comment by robertvorthman** [comment]
Thanks! I installed the git version and now triggers are working.  Your plugin is going to save so much earth with people's homes saving energy when nobody is home.

I have iBeacons turning stuff on, and this plugin turning stuff off (plus Ecobee sensors).

**Comment by PeteLawrence** [comment]
Great, glad that you've found it useful.  I've just pushed v0.3.5 to npm which adds in support for triggers.

**Comment by robertvorthman** [comment]
I get a lot of false positives and I'm not sure how to troubleshoot it.  I have 2 iPhones with a 32 minute threshold.  It seems like the ANYONE occupancy sensor says No when it really should have detected at least one of the iPhones.  I looked for the seen.db.json but I can't find where it is.
