### ISSUE TITLE
The 'ANYONE' sensor is confusing if you can't tell which sensor it is

### ISSUE THREAD

**Issue by jchadwick** [PeteLawrence/homebridge-people#18]
I love the intent behind the ANYONE sensor.  When/if you can actually determine which one it is, it will be an awesome feature.  Right now it seems like some may find it more confusing than helpful so perhaps it should be optional.

That said, I have two issues with the 'ANYONE' sensor, both of them relating to the fact that the sensors do not have names everywhere (as discussed in #15):
1. I was surprised when I first configured the plugin with **two** people and **three** occupancy sensors showed up in the list.  Came to find out one of them was the 'ANYONE' sensor, which makes a lot of sense.
   - *_Possible fix: *_  Update the documentation for the plugin to indicate that the ANYONE sensor will be added automatically
2. It's not possible to know for sure which sensor the "ANYONE" sensor actually is.  Yes, I know from #15 that it _should_ always be the last one in the list, but that doesn't seem like a very good answer since it's possible that different applications may choose to sort them differently for some reason.
   - *_Workaround: *_  Update the documentation for the plugin to mention that the ANYONE sensor _should_ be the last sensor in the list.  Again, not sure this will actually always be true...

**Comment by luc-ass** [comment]
Are you using Eve for your HomeKit management? It shows the name for each device.

**Comment by coliflower** [comment]
Hi, I just installed the people plugin for two people (two iPhones). But I also see a third one with the name „ANYONE“ …

What exactly does it means, please ?

**Comment by PeteLawrence** [comment]
The ANYONE device will show as 'ON' if either of your iPhones are present, or 'OFF' if neither of your iPhones are present.  It allows you to easily setup triggers that activate when 'Anyone' arrives home, or when the last person leaves home, rather than a specific person.

eg1. Turn on porch light when anyone arrives home
eg2. Set thermostat to 'Away' when the last person leaves the house.

**Comment by coliflower** [comment]
Thanks a mit for your explanation !

Is there also Dome good explanation how to setup tirggels ?

**Comment by coliflower** [comment]
Sorry for autocorrect ...

Thanks a lot for your explanation !

Is there also some good explanation how to setup triggers ?

**Comment by aecom** [comment]
hi thanks for that plugin
is there way to cancel ANYONE from showing?
thanks

**Comment by cybertza** [comment]
u can code it out in the index.js if you so wish, best is to just remove it from fav's and put it in an unused room
