### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by PeteLawrence** [PeteLawrence/homebridge-people#2]
From a very limited amount of testing, I've found that a threshold of 15 minutes seems to work well for the phones that I have around, but for different phones this may or may not work.

The following command (tested on a Mac) should print a line that includes the current time every time the target device responds to a ping request.  

```
ping <target ip> | awk '/^[0-9]+ bytes from / { "date" | getline pong; close("date"); print pong":",$0; }'
```

Please let me know what thresholds work for your phone/combination of apps running on it.  
- iPhone 5, no running apps, 3 email accounts (iCloud, IMAP and Exchange) - 15 minutes

**Comment by tvillingett** [comment]
I was looking at the code, and printed debug every time it pings. And it pings only when you "look" at the sensor in the Eve app. Does the ping time calculate from last sucessful ping - which is only when you use the app, will it then be a "blind spot" for up to 15 minuters?
