### ISSUE TITLE
different type of sensor

### ISSUE THREAD

**Issue by peshay** [PeteLawrence/homebridge-people#20]
If I want to make automation with these sensors in Homekit, I can only trigger an action if the device is spotted with ping. But I actually want to trigger action when no device is spotted. I guess the sensor in Homekit needs to be a different one to achive this. Do you have any idea how to solve this?

**Comment by PeteLawrence** [comment]
Are you using the Apple Home app? From a quick look it looks like this works as you describe.  I use the Elgato Eve app, which allows you to setup triggers on both the present and away transitions.

**Comment by peshay** [comment]
Okay that actually would do it. Sadly in Eve App it shows me the 3 triggers as "People", so I don't know who is who. I have another Home app which shows me the names, so that works. 

But I don't really like the idea of having ton of apps for the automation. I already have Z-Way to handle my z-wave devices, then Home App and now another App.
Actually I think it would be really cool to have your people already as widget in z-way. As I'm not so experience with javaScript, maybe it's an easy task for you to implement that? 
https://github.com/Z-Wave-Me/home-automation/wiki/How-to-create-a-widget

If you are not interesset, I may give it a try on my own.
