### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by tomto147** [PeteLawrence/homebridge-people#22]
I have installed people plugin on my raspberry pi without problems and configured it directly to two IP adressess of my iPhones. Run the home bridge app with no error messages. Both iPhones do show in EVE app on my iPhone, but they report as "away" although at home and more than 15 min has passed.

Any ideas what can be wrong?
All of the other plugins work properly

**Comment by PeteLawrence** [comment]
Have you chmod'd the ping executable?

`sudo chmod u+s /bin/ping`

**Comment by tomto147** [comment]
Ohhh this was it ;-) Sorry I have missed the note... Thanks!

**Comment by tomto147** [comment]
Strange... I have changed ip to my iPhone name (because it keeps changing IP), and now it no longer recognizes the device. I have spaces in the device name. Is it allowed?
