### ISSUE TITLE
Where does the log live? 

### ISSUE THREAD

**Issue by RickNunn** [PeteLawrence/homebridge-people#24]
Love the plugin, working really well for me for them most part. But I'd really like to have a look at the logs. 

However I'm not managing to find them. I've done a search for seen.db.json and come up empty handed. I've looked in the log folder (/var/log) and done `find . -name seen.db.json` but nothing. 

If anyone could point me in the right direction that would be rad.

**Comment by PeteLawrence** [comment]
Hi,

There should be a file for each device you're monitoring in the ~/.homebridge/persist folder.

Pete

**Comment by RickNunn** [comment]
Got it, thanks Pete!
