### ISSUE TITLE
iOS 10 Home app does not automate upon "away" state

### ISSUE THREAD

**Issue by deanlyoung** [PeteLawrence/homebridge-people#25]
It would be nice to have a second default "person" titled "NO ONE", which would trigger when no people are detected. I understand this may be possible through another app, like Elgato, but it doesn't make as much sense to download the app when you don't have any Elgato accessories. BTW, I really like this elegant solution for detecting presence.

**Comment by bahlo** [comment]
[This app](https://itunes.apple.com/us/app/home-smart-home-automation/id995994352) supports trigger on deactivation, so it's built into HomeKit, but not the Home app. It's a bit pricey, but it's a great app.

**Comment by deanlyoung** [comment]
Thanks @bahlo! I got it working with some "no one" trigger code I found in the pull requests for this repository that haven't been merged yet.

**Comment by PeteLawrence** [comment]
Hi @deanlyoung,

The no one code has now been merged in and is available via NPM.
