### ISSUE TITLE
Error: listen EADDRINUSE :::51828

### ISSUE THREAD

**Issue by oberstmueller** [PeteLawrence/homebridge-people#26]
Hi, after installing v. 0.4.0 my Homebridge gives me this Error ( Error: listen EADDRINUSE :::51828 ) when i try to start it. When i install v. 0.3.5 again all works fine.

**Comment by benzman81** [comment]
The plugin now starts a server that uses port 51828 by default. If this is in use on your machine you can fix this by adding the configuration parameter "webhookPort" with a different port, i.e. 51829.
