### ISSUE TITLE
Location Push Host Name

### ISSUE THREAD

**Issue by erfinb** [PeteLawrence/homebridge-people#28]
Is there a way we can use a host name in place of an IP Address?

http://youripaddress:51828/?sensor=[name]&state=true

Also, do you literally replace [name] with a name such as Erfin or does it need to be [Erfin]

Lastly, I'm still not great with GitHub, is this the best way to communicate with one another regarding questions which may be viewed as issues, or is there another more appropriate place to post messages/questions like this?

Thanks!

**Comment by erfinb** [comment]
I figured out the username goes without the brackets. Whenever the enter sets the person to true it works really well, however when it sets it to false HomeKit sees the change and then quickly reverts back to triggered. Any ideas?

**Comment by creedda** [comment]
#30 I think This request should be consolidated here. Same issue?

**Comment by erfinb** [comment]
We can consolidate them over to #30 if you would like as the description there is more relevant :)

**Comment by erfinb** [comment]
Closing as a merge to Issue #30
