### ISSUE TITLE
Please make location of seen.db configurable or use the persistant storage of homebridge to save it

### ISSUE THREAD

**Issue by Danimal4326** [PeteLawrence/homebridge-people#3]

**Comment by PeteLawrence** [comment]
Thanks for the suggestion. I can't see that homebridges persistent storage is made available to plugins (please correct me if I'm wrong), but can definitely make the path configurable.

**Comment by Danimal4326** [comment]
Ok maybe use the .homebridge folder that holds the config files and persistent storage folder the default?

**Comment by PeteLawrence** [comment]
The module will now use the .homebridge persist folder. I've published the update to npm.  Thanks for the suggestion.

**Comment by Danimal4326** [comment]
Great! thanks
