### ISSUE TITLE
Geo Location not taking precedence

### ISSUE THREAD

**Issue by sbels** [PeteLawrence/homebridge-people#30]
I have this plugin working well by monitoring for certain devices on my local network. In trying to improve the speed of detection, I've also configured geo location leveraging IFTTT Maker Channel to send the http commands (have also tried Locative with same results). I can see that homebridge receives the commands promptly but it appears the occupancy status is not being correctly overriden.

For example:
- threshold set to 15 minutes
- Say I leave at 8:00 AM (last seen on network at 8:00 AM)
- IF triggers the event to show I left at 8:02 AM
- Homebridge receives the event, temporarily shows Not Present but then immediately switches back to present
- At ~ 8:15 AM sensor is correctly updated to Not Present

At 8:02, I would expect my occupancy to update to Not Present. It looks like that happens for a split moment but then reverts back to Present. It is not until ~ 8:15 that it actually updated to Not Present. Not sure what value Geo Location is adding in this case?

How can I have Geo Location help Homebridge know my presence more quickly? Or, is this not the way it was designed?

**Comment by erfinb** [comment]
I'm having the same issue 🙂

**Comment by erfinb** [comment]
@PeteLawrence any ideas on this?

**Comment by nitaybz** [comment]
Joining the problem, having the same issue...

**Comment by creedda** [comment]
Have the same issue. Looks like we need a way to toggle if we want the ip ping to override the ibeacon http push.

**Comment by benzman81** [comment]
This will be fixed with pull request "Major Rework  #35". If a webhook is called for a target, the ping will pause for the configured threshold.

**Comment by PeteLawrence** [comment]
This should now be fixed in v0.5, thanks to @benzman81.
