### ISSUE TITLE
geolocation - status not updating

### ISSUE THREAD

**Issue by andyrooo82** [PeteLawrence/homebridge-people#32]
Hi,

I'm using the people-geolocation plugin but it doesn't seem to update my presence so the No One is always being showed as triggered.

I have setup port forwarding which seems to work fine. In my browser I can enter http://mypublicipaddress:51829/?sensor=[Andy]&state=true 

and i get the response: {"statusChanged":true}

the plugin is running ok

Dec 20 18:28:29 raspberrypi homebridge[521]: [12/20/2016, 6:28:29 PM] [People] Initializing GeoFence accessory...
Dec 20 18:28:29 raspberrypi homebridge[521]: [12/20/2016, 6:28:29 PM] [People] WebHook: Started server on port '51829'.

I think the issue might be that in my persist folder i do not have a file called "person_Andy"

my persist folder is in /var/homebridge/persist

has anyone got any ideas of what i'm doing wrong here, i'm stumped.

thanks in advance.

**Comment by ToddGreenfield** [comment]
I am messing around with this right now and got mine to work (I think). Try removing the brackets from your name and give it a shot.
http://mypublicipaddress:51829/?sensor=Andy&state=true

I was testing mine by disconnecting from home wifi and then issuing the http commands in a browser to simulate status changes.

**Comment by andyrooo82** [comment]
wow, you're a genius!! thanks so much Todd - works like a charm now.

**Comment by erfinb** [comment]
Are you all seeing these trigger automations consistently without opening the Home App? Are the people Away resulting in the user being untriggered or are they still triggered when exiting the geofences area?

**Comment by andyrooo82** [comment]
Hey,

I can confirm that triggers are being triggered (Home and Away) without the Home app being open or in the background.

The geofence areas seems to be working fine.

**Comment by ToddGreenfield** [comment]
I think I am seeing intermittent triggers when the app is not open, and when i open it the automation gets triggered. Will have to continue to monitor-

**Comment by erfinb** [comment]
Mine is not usually triggering after I open the app, almost as though it is too late to run the automation. Either it triggers on its own without opening the app, or I'm out of luck. 😕

**Comment by andyrooo82** [comment]
I've not had a problem with geofences being triggered. The automations are being run from my Apple TV. I setup the rules in the elgato eve app. I'm using IFTTT/ Maker Channel on my iPhone and Locative on my wife's iPhone to send the http commands when we're home and away. 

When I set up the rules I used the anyone and no one people as I don't live on my own. 

I do also have a crontab setup to reboot my raspberry pi at midnight and midday as I was seeing issues with homebridge being unresponsive.

**Comment by erfinb** [comment]
Mine is running on my Mac and Apple TV. Is your Apple TV hard wired?

**Comment by erfinb** [comment]
Also what power settings is your Apple TV using?

**Comment by andyrooo82** [comment]
My Apple TV is connected via wifi. It's also set to go to sleep after 15 mins so it's mainly in sleep mode most of the time. I don't really use the Apple TV for anything else other than home automation.

**Comment by erfinb** [comment]
And you have a 4th generation Apple TV?

**Comment by andyrooo82** [comment]
Is it possible that when your mac goes to sleep it drops off the network??

**Comment by andyrooo82** [comment]
Sorry didn't see your question. Yep 4th gen

**Comment by erfinb** [comment]
I have it set to never sleep. And I have Splashtop so I remote in and check the homebridge he and the triggers are all there in real time. Just some are carried out as automations on their own and a majority don't seem to regrow yer with HomeKit until I open the home app. Does that make sense?

**Comment by erfinb** [comment]
Sorry that was a bit garbled lol typing on my iPhone.

**Comment by erfinb** [comment]
Register with**** instead of regrow yer lol

**Comment by andyrooo82** [comment]
Not sure what you mean to be honest. What are you getting the Home and away to do? Turn off/on lights??

**Comment by erfinb** [comment]
I have it running various scenes in some cases, and in others it's doing things like opening garage doors. The triggers always report to the homebridge immediately, as I can see it in the homebridge log, however the occupancy triggers aren't always seen by HomeKit to actually carry out an automation. In these cases, I open the Home app which then seems to check in with the homebridge and see that occupancy has been detected, usually when I have to force this check then the Home app didn't carry out the automation. I would say less than half of the time lately that HomeKit seems to be seeing occupancy changes on its own without opening the app which means most of my automations based on occupancy aren't functioning. Is that a little better, lol it's an awkward thing to describe.

**Comment by andyrooo82** [comment]
how are you using the people plugin, have you set it up to be IP or geofence (i had massive issues with IP, sometimes the lights would come on at 4am when our phones would drop off then on the network again). If geofence, what app are you using to send the http command? how did you setup the rule that use the occupancy as a trigger? e.g. i used elgato eve app. do you have multiple occupancy at home?

**Comment by ToddGreenfield** [comment]
Chiming in here- My hub is my iPad Mini, which is always plugged in on my desk. Whether is it awake or not depends on when I last touched it.
The one main automation which I had setup was, when detecting People's "no One" sensor firing (using combo IP+Geo (via Locative), it would run the Leave Scene (which would turn off all lights, lock the front door, and arm my security via envisalink plugin).
I have found that it only works when I open the home app on my phone to check and see if it worked.
I am curious if using the iPad as the hub might be one of the challenges?
Also curious if there is something I could do on the RPI to trigger a wakeup/refresh/check or something on the iPad Hub?

**Comment by andyrooo82** [comment]
@ToddGreenfield i think you may be onto something here. i don't seem to have this problem using the RPi as a hub. i suppose you could setup a script to ping the ip of your iPad.

when i used the IP instead of the geofence i found my phone would drop off the network and wasn't really reliable so i'm sticking with just geofence which works fine. 

i even tried changing the setting on my iPhone to pull emails every 15 mins so it stayed on the network but this didn't seem to help.

**Comment by andyrooo82** [comment]
i wonder if this is covered over here [https://github.com/nfarina/homebridge/issues/1006]

**Comment by andyrooo82** [comment]
i wonder if this is covered [here](https://github.com/nfarina/homebridge/issues/1006)

**Comment by erfinb** [comment]
Hey @benzman81 what are you using for your homebridge hub, a Mac, Raspberry Pi, etc. 🙂?

**Comment by benzman81** [comment]
@erfinb using a Synology Diskstation without sleepmode and run Homebridge inside a docker container. My assupmtion is that iOS 10.2 is responsible for this bug. Anyone has this issue using iOS < 10.2. I cant remember having issues before.

**Comment by ToddGreenfield** [comment]
@andyrooo82 I agree, it sounds like the same issue.
Also to clarify, I am using an RPI for running homebridge+plugins. I am using my iPad for remote access to Apples's Homekit.
I am running 10.2 on all-
