### ISSUE TITLE
how to read log-file

### ISSUE THREAD

**Issue by farstreet** [PeteLawrence/homebridge-people#33]
Based on what I found back in this repository, I expected to find log-files for the people that I'm tracking in the /persist folder.   There are indeed two files, person_10.0.1.110 and person_10.0.1.114, where the file-names are referring to the internal IP addresses of the two iPhones that I have configured in the config.json file.   Firstly I'm surprised that the file-name doesn't contain the names I used in the config, but as such that is not a problem, based on the filename I know who is who.   Looking at the time of last update (file properties), I can see they both get updated regularly, but the content doesn't tell me anything.   It's just one line with a bunch of numbers.   Tried to recognize a date/time format in there, but without luck.     

What am I doing wrong here?    Running Homebridge on OSX.

Thanks, Jurgen

**Comment by benzman81** [comment]
Everything is fine here. The files are not used as log files. THe are used to remember the last successful ping. The number you are seeing is a timestamp. You can use this page http://www.epochconverter.com/ to convert it,  for example.

**Comment by farstreet** [comment]
So there is no logging of all pings and the returned status?   I saw references to a seen.db.json file but I must have misinterpreted that then.

**Comment by benzman81** [comment]
Not anymore. The commit of the first version contained this logging, but must have been removed.
