### ISSUE TITLE
ios Notifications enhancement proposal

### ISSUE THREAD

**Issue by farstreet** [PeteLawrence/homebridge-people#34]
Hey Pete,

Maybe an idea for an enhancement...   Since iOS 10.2, the status-change of the sensors created by your plugin can be pushed as a Notification on the iPhone.    Pretty cool is you want to know when someone arrived or left home.  

However, the Notification itself doesn't give a lot of info.    Check out the attached image, all it says is "Occupancy detected in XXX" (in this particular example, Stewart Village is the name of my Home, Presence is the name of the Room where I assigned the switches to). 

Would be awesome if the name of the sensor (Anyone, No One, Person A, Person B, ...) could be used + an indication whether it's an arrival (home) or a departure (away).

Not sure though whether you have any way of controlling that.
 
![img_0692](https://cloud.githubusercontent.com/assets/24705229/21418031/6090b314-c7d3-11e6-8397-b1242dde9e6c.PNG)

Thanks, Jurgen

**Comment by rcoh80** [comment]
One work-around, though far from ideal, would be to assign your presence sensor to a room named after who your presence sensor relates to. E.g name a room Jurgen, assign your presence sensor to that room and your notification will then be 'occupancy detected in Jurgen'

**Comment by farstreet** [comment]
Genius :)   I love the idea as a temporary workaround.

**Comment by benzman81** [comment]
I don't think that we can influence the text. But as workaround you can put each occupancy sensors in ist own room, i.e. ALL, Person 1, Person 2. Just an idea.

**Comment by benzman81** [comment]
Lol, I should have hit refresh first ;-)

**Comment by farstreet** [comment]
Just tried this but noticed that changing the name of the room for one of the buttons actually makes all buttons change to that room.     Damn 👎

**Comment by benzman81** [comment]
Oh, I see. This is due to implementation of the plugin that only represents one accessesory but exposes multiple services. I can imagine that changing the plugin to be a platform instead of an accessesory will fix this.

**Comment by farstreet** [comment]
Could be, but if programming would be needed for a workaround, I would rather see the effort go into the Notification itself.   But again, it will depend on how the Notification process works exactly and to what extent the information sent to it can be modified.

**Comment by benzman81** [comment]
It is not possible to change the notification. This is done by homekit.

**Comment by farstreet** [comment]
Then indeed it would come down to a workaround that allows different rooms to be used for the different buttons, including the Anyone and NoOne buttons which are generated automatically (and which you want to change behavior based on changing occupancy of all people.

**Comment by erfinb** [comment]
@benzman81 is there anyway that we can use your version in the pull request without @PeteLawrence approving it first?

**Comment by benzman81** [comment]
yes there is. i am currently Fixing a mysterious bug that spawns multiple pings although it shouldnt. So you should wait a bit. If you still want to try it you can just do "npm install benzman81/homebridge-people" this instals a module from github, not from the npm repo.

**Comment by erfinb** [comment]
Thank you for your hard work and I will wait until you say something is ready 🙂 thanks!!!

**Comment by benzman81** [comment]
@erfinb you should be fine now. Happy testing. Feel free to open an issue in my repository.

**Comment by benzman81** [comment]
@farstreet if the pull request is merged, than you can use different rooms to have better notifications ;-)

**Comment by farstreet** [comment]
Any idea when ?  Not dependent on you if I understood well.

**Comment by benzman81** [comment]
@farstreet: you can use the way described above or wait until after the holidays. @PeteLawrence will approve then.

**Comment by PeteLawrence** [comment]
I've just published 0.5 which includes the ability to assign individual sensors to their own rooms.  Not ideal, but until (if) Apple update the notifications to include the name of the accessory there's no real other option.
