### ISSUE TITLE
When away from home-wifi: 2 of my 5 sensors show 'Not Responding' in Home, other three work fine

### ISSUE THREAD

**Issue by jojost1** [PeteLawrence/homebridge-people#41]
Weird issue I found.. My phone works, anyone/no-one works, two other phones do not work and show 'Not Responding' when away from home wifi only. **When on local wifi, all sensors work.**

**Comment by GatoPharaoh** [comment]
but the Home App as a whole does work in these phones when away?

**Comment by jojost1** [comment]
Yes, other sensors by HomeBridge-people work fine as well as my thermostats and lights (which are native HomeKit).
