### ISSUE TITLE
Not being detected

### ISSUE THREAD

**Issue by ehusar** [PeteLawrence/homebridge-people#42]
I have everything setup and Homebridge is running without error on my RPi 3.  I have my phone details entered but I never show detected. Here is my config file.    Other than installing the and rebooting Homebridge is there anything else I am missing to get this working?
{
                "platform": "People",
                "threshold": 15,
                "anyoneSensor": true,
                "nooneSensor": false,
                "webhookPort": 51828,
                "pingInterval": 10000,
                "ignoreReEnterExitSeconds": 0,
                "people": [{
                        "name": "Ed",
                        "target": "Eds-iPhone",
                        "threshold": 15,
                        "pingInterval": 10000,
                        "ignoreReEnterExitSeconds": 0
                }

**Comment by ehusar** [comment]
It looks like if I use the IP address of an iPhone then it works.  Using the name of the iPhone doesn't work for me. I have tried two different iPhones without any luck.

**Comment by benzman81** [comment]
You need the name of your phone in the network. If ip is working, than there must be something wrong with DNS to get the ip from the name. Maybe you can look at your routers ui interface to check for its name. Also, you can try to ping the name manually. The plugin doesnt do magic, just ping ;-)

**Comment by ehusar** [comment]
Yes, I looking at my Apple Extreme to get the names of the iPhone. The names show up by default so that is where I got it from.

Let me try to ping the name directly.

**Comment by ehusar** [comment]
This is interesting.  This is a ping from both the iPhone name and the IP.  I xxx'ed out the last two spots of the addresses.  But they are different addresses?  I have not clue where/why the 198 is coming from.  It is the 10.0.xxx.xx that shows up on the Apple Extreme.

Also, unlike a ping to a computer where is keeps returning the ping the ping on the iPhone only returns once.   

`pi@Development:~/.homebridge $ ping Eds-iPhone
PING Eds-iPhone (198.105.xxx.xx) 56(84) bytes of data.
^Z
[4]+  Stopped                 ping Eds-iPhone
pi@Development:~/.homebridge $ ping 10.0.112.18
PING 10.0.112.18 (10.0.xxx.xx) 56(84) bytes of data.

**Comment by benzman81** [comment]
maybe there is an entry for that name in /etc/hosts file?

**Comment by ehusar** [comment]
It appears to have something to do with the Airport system and how it boots up.  I found a post about it but I don't know how to fix it yet.

For now I will just use IP addresses.   Thanks.
