### ISSUE TITLE
How to adjust time / timezone?

### ISSUE THREAD

**Issue by rafacampoamor** [PeteLawrence/homebridge-people#44]
My hombridge is logging with one hour "delay" from my timezone. Raspi is with the correct time and timezone, but home bridge must be using GMT. ¿Is there a way to solve this? I need this to be accurate for the "people" plugin to work and I'm completely lost.

**Comment by benzman81** [comment]
For the people plugin the time zone is not relevant since it only measures the difference between timestamps.

**Comment by PeteLawrence** [comment]
Yeah, timezone shouldn't matter.  Might be related to #43
