### ISSUE TITLE
Considered Away when off Wifi but inside geofence

### ISSUE THREAD

**Issue by sbels** [PeteLawrence/homebridge-people#47]
I'm sure this is by design but I'd like to offer an alternative approach for consideration (maybe as a configuration). For those that setup both IP presence & Geofence...

Change state from Home -> Away if:
IP not present AND outside geofence

Change state from Away -> Home if:
IP becomes present OR inside geofence

Thoughts?

Currently, I'm considered Away if I switch wifi off for a few minutes (or perhaps if my phone dies).

**Comment by nitaybz** [comment]
@sbels  That's already the way it works... benzman81 set it to work this way, even if wifi is off it will trigger 'Home' and stay that way as long as it got the webhook (state=true).
Though, once you turn on your wifi, it will trigger auto 'Away' when wifi is disconnected.
to only rely on the geofence webhook is a bit risky, sometimes it won't fire when you leave the house and your automation will not be triggered.
I think this is the best solution cause usually when you come home with the wifi ON you won't turn it off while you're still in the house. The best thing in this plugin is that the geofence acts as a fallback in case the the wifi is turned OFF when coming home.
