### ISSUE TITLE
How long are logs kept?

### ISSUE THREAD

**Issue by luc-ass** [PeteLawrence/homebridge-people#5]
Hey, I just wanted to ask how long the logs are stored. I'm actually just thinking about space...

**Comment by PeteLawrence** [comment]
Only the IP and the most recent time that the IP was seen is logged.  At the moment these are stored indefinitely regardless of whether the IP is still listed in the config file or not.  The overhead per host is less than 30 bytes, so storage space should not be an issue.

I shall look at removing old seen files once the IP has been removed from the config file however.

**Comment by luc-ass** [comment]
Ah ok. that's even fewer entries than I expected. Nice job btw.
