### ISSUE TITLE
Problems with Cache Directory and Permission

### ISSUE THREAD

**Issue by Elch08** [PeteLawrence/homebridge-people#53]
I have problems with the following line in the config.json file: ""cacheDirectory": "./.node-persist/storage", 
I always get the following error when starting homebridge:

_[2017-01-17 20:37:56] Initializing People platform...
/usr/lib/node_modules/homebridge-people/node_modules/node-persist/node_modules/mkdirp/index.js:74
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge-people/node_modules/node-persist/storage'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (/usr/lib/node_modules/homebridge-people/node_modules/node-persist/node_modules/mkdirp/index.js:55:12)
    at sync (/usr/lib/node_modules/homebridge-people/node_modules/node-persist/node_modules/mkdirp/index.js:61:24)_

Then Homebridge is crashing. I can, however, start homebridge with the command "sudo homebridge" or when logged in as Root. So it seems to be a permission error but I have no idea which one. So I always deleted the above line for the Cache Directory, because you marked it as "optional". But I would prefere to use the line in the config.json. Can you please help me ?

Thanks in advance
Björn #

**Comment by benzman81** [comment]
This is exactly the issue why it is changeable via configuration. Just point it to a directory with permissions.

**Comment by Elch08** [comment]
I tried and put in a different Directory, where I presumably have permission. But the error Code ist exactly the same. Maybe I did not get what you meant by "poiting it to a Directory with permission". Do you have an example ?

**Comment by benzman81** [comment]
Hmm, thats weird. Anbexample would be:

"cacheDirectory": "/home/myuser/people-storage"

Maybe try to chmod 777 to that directory as a test.

**Comment by Elch08** [comment]
Super. I did the following: "sudo chmod -R 777 /usr/lib/node_modules/homebridge-people/node_modules/node-persist/storage". This gave me permission and now the error message is gone.
