### ISSUE TITLE
Plugin and AppleTV Hub

### ISSUE THREAD

**Issue by poudenes** [PeteLawrence/homebridge-people#54]
Hi there,

does this plugin work when the appleTV is the hub in house?
I can't see the lines in the log file anymore.

{
                "platform": "People",
                "anyoneSensor": true,
                "threshold": 15,
                "pingInterval": 10000,
                "ignoreReEnterExitSeconds": 0,
                "nooneSensor": true,
                "cacheDirectory": "/root/.homebridge/people-storage",
                "people": [{
                        "name": "Peter",
                        "target": "192.168.178.38"
                         },{
                        "name": "Cay",
                        "target": "192.168.178.59"
                }]
        }

**Comment by benzman81** [comment]
Should work. I uses it with an AppleTV4 and sleep mode.

**Comment by poudenes** [comment]
Did uninstall the plugin and reinstalled. 

Jan 24 19:22:05 osmc homebridge[28970]: 1/24/2017, 7:22:05 PM > [1/24/2017, 7:22:05 PM] Loaded plugin: homebridge-people
Jan 24 19:22:05 osmc homebridge[28970]: 1/24/2017, 7:22:05 PM > [1/24/2017, 7:22:05 PM] Registering platform 'homebridge-people.People'
Jan 24 19:22:05 osmc homebridge[28970]: 1/24/2017, 7:22:05 PM > [1/24/2017, 7:22:05 PM] Registering accessory 'homebridge-people.PeopleAccessory'
Jan 24 19:22:05 osmc homebridge[28970]: 1/24/2017, 7:22:05 PM > [1/24/2017, 7:22:05 PM] Registering accessory 'homebridge-people.PeopleAllAccessory'

Jan 24 19:22:06 osmc homebridge[28970]: 1/24/2017, 7:22:06 PM > [1/24/2017, 7:22:06 PM] Initializing platform accessory 'Peter'...
Jan 24 19:22:06 osmc homebridge[28970]: 1/24/2017, 7:22:06 PM > [1/24/2017, 7:22:06 PM] Initializing platform accessory 'Cay '...
Jan 24 19:22:06 osmc homebridge[28970]: 1/24/2017, 7:22:06 PM > [1/24/2017, 7:22:06 PM] Initializing platform accessory 'Anyone'...
Jan 24 19:22:06 osmc homebridge[28970]: 1/24/2017, 7:22:06 PM > [1/24/2017, 7:22:06 PM] Initializing platform accessory 'No One'...
Jan 24 19:22:06 osmc homebridge[28970]: 1/24/2017, 7:22:06 PM > [1/24/2017, 7:22:06 PM] WebHook: Started server on port '51828'.

but not working....

always on "No one"

**Comment by poudenes** [comment]
Everything else is working... Im running on OSMC for kodi. I can't fint out where the problem come from. Loaded Homebridge on my OSX and installed the plugins and then i got the Anyone sensor working again.
