### ISSUE TITLE
anyoneSensor false, but still get one in home app

### ISSUE THREAD

**Issue by jaquesp** [PeteLawrence/homebridge-people#63]
Hi - I have installed the homebridge-people plugin and have configured as follows:

`        {
        	"platform": "People",
        	"threshold" : 8,
        	"anyoneSensor" : false,
        	"nooneSensor" : false,
        	"webhookPort": 51828,
        	"pingInterval": 10000,
        	"ignoreReEnterExitSeconds": 0,
        	"people" : [
                {
                	"name" : "Paul", 
                	"target" : "192.168.0.22",
                	"threshold" : 8,
                	"pingInterval": 10000,
                	"ignoreReEnterExitSeconds": 0
            	}
                ]
        },`

Despite setting anyoneSensor to false, I still get one in the Home App - is there something wrong with my configuration?

Thanks in advance!

**Comment by benzman81** [comment]
Duplicate of #50

**Comment by jaquesp** [comment]
Thanks @benzman81 I did take a look but couldn't see a duplicate! Thanks!

**Comment by b3nj1** [comment]
I'd submit a pull request, but don't know the cleanest way in js to fix this:
    this.anyoneSensor = config['anyoneSensor'] || true;

config['anyoneSensor'] = false  -> "false || true" -> that's still true.

Instead, something like this would let it be configured to false, but still default to true when not supplied.
    this.anyoneSensor = config['anyoneSensor'] === undefined ? true : config['anyoneSensor'];
