### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by johnnygoodface** [PeteLawrence/homebridge-people#67]
Hi, 
Maybe I'm stupid, but I get a Error: EACCES: Permission denied, mkdir '/usr/lib/node_modules/homebridge-people/node_modules/node-persist/storage' when I start Homebridge
I'm using the default key: "cacheDirectory": "./.node-persist/storage"
What security should I apply to what folder?
Thx

**Comment by johnnygoodface** [comment]
Found the answer in another tread: I did the following: "sudo chmod -R 777 /usr/lib/node_modules/homebridge-people/node_modules/node-persist/storage". This gave me permission and now the error message is gone.

**Comment by aguaman15** [comment]
For me, the folder path was slightly different. I used this Terminal command:

"sudo chmod -R 777 /usr/lib/node_modules/homebridge-people/node_modules/node-persist"

The "-R" option makes the command recursive, which means it will give permissions to the folder and any folder and files within that folder. So even if you happen to have a "storage" folder, this will still work.
