### ISSUE TITLE
Cannot get status change

### ISSUE THREAD

**Issue by tvillingett** [PeteLawrence/homebridge-people#7]
I have set up two persons iphones with IP-addresses that works when I ping them from another computer on the same local network.
The status newer changes in the Eve app. what can I do to debug?

**Comment by PeteLawrence** [comment]
Can you ping them from the device running Homebridge?

**Comment by tvillingett** [comment]
I tried that now, and yes I can ping them.

**Comment by oberstmueller** [comment]
The Pi need Sudo to Ping.You can fix it with "sudo chmod u+s /bin/ping". Then ping and homebridge-people should work.

**Comment by armins2k** [comment]
Hi,
I have the same problem. I can ping my phone from my Pi and the people plugin loads fine on homebridge start, but the Home app doesn't see my phone.
Anything else I can do to troubleshoot?

Thanks!

**Comment by tvillingett** [comment]
Not in my install, ping works fine. I tried the suggested chmod also, but still "NO" as status only. Can it be something about writing the persistant file?

**Comment by PeteLawrence** [comment]
@tvillingett: Assuming that you're using the latest version from npm (```npm update -g homebridge-people```), the plugin will use the standard homebridge persist folder so permissions shouldn't be an issue.  Could you paste the output from ```ls -la /home/pi/.homebridge/persist``` where '/home/pi' is the home directory of the user that you're running and I'll take a look.

**Comment by PeteLawrence** [comment]
@armins2k: Are you saying that the Home app doesn't show your phone at all, or that it doesn't show it as being online?

**Comment by tvillingett** [comment]
Seems like it don't write anything:
```
pi@thethingbox ~/.homebridge/persist $ ls -la
total 36
drwxr-xr-x 2 pi pi  4096 Mar  3 20:21 .
drwxr-xr-x 4 pi pi  4096 Mar  6 13:18 ..
-rw-r--r-- 1 pi pi   705 Mar  6 19:13 AccessoryInfo.CC243FE4DF34.json
-rw-r--r-- 1 pi pi 23624 Mar  6 21:24 IdentifierCache.CC243FE4DF34.json
```

**Comment by tvillingett** [comment]
I copied the settings to home/.homebridge and run the homebridge again as root, but no success.

**Comment by armins2k** [comment]
Home app shows my phone but it's always non active. Checked the IP address couple of times, also my config file seems fine.

**Comment by PeteLawrence** [comment]
You could try adding the following after ```ping.sys.probe(target, function(isAlive){``` within index.js, followed by a restart of homebridge.

```this.log('ping', isAlive);```

If you see 'true' in the output it's an issue with the ping, otherwise it's a problem writing the seen file.

**Comment by tvillingett** [comment]
If found the problem: the configuration file does not use the "target" i uses "ip".

The settings example should be updated. It works for me now when I did this.
I debugged it with this.log and got undefined on the IP adress, so I looked for the references - which was zero to "target" :)

**Comment by PeteLawrence** [comment]
Ah ok, glad you got it working.  I renamed 'ip' to 'target' towards the end of last week but hadn't got around to pushing it to npm.  I assumed everyone would find the plugin via npm and use the *old* config keys that are documented on npm still, rather than the new ones documented on Github.

I'll go push a new version to npm now so that the documentation is in sync with Github.

Thanks for trying out the plugin!

**Comment by PeteLawrence** [comment]
Changes released in 6e0bb33

**Comment by armins2k** [comment]
okay, mine wasn't the 'IP' 'target' problem. Just made the suggested change to the index.js file and now I see 'true' in the output and its working in Home app.
So can I leave the index file like that or is the problem still not solved??
Sorry but I'm not an expert ;)
Thanks for the help!!

**Comment by maciej-wilczynski** [comment]
I have a solution, homebridge-people uses ping@0.1.10 which is old version of package. The workaround is simple:
edit file node_modules/ping/lib/ping-sys.js and replace 30 line to:
`ls = cp.spawn('/bin/ping, ['-n', '-w', '2', '-c', '1', addr]);`

or wait for homebridge-people update

**Comment by alexbaldwin** [comment]
@wiqert was that the only change? I am not able to get this plugin working correctly at all.

**Comment by maciej-wilczynski** [comment]
Yep, Only this one. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by i3laze** [comment]
> I have a solution, homebridge-people uses ping@0.1.10 which is old version of package. The workaround is simple:
> edit file node_modules/ping/lib/ping-sys.js and replace 30 line to:
> `ls = cp.spawn('/bin/ping, ['-n', '-w', '2', '-c', '1', addr]);`
> 
> or wait for homebridge-people update

@wiqert Thanks! That fixed my HomeBridge running in Docker (oznu/docker-homebridge).

But.. you missed ' . Correct line 30 would be:
`ls = cp.spawn('/bin/ping', ['-n', '-w', '2', '-c', '1', addr]);`

I suggest this workaround to be pulled.
