### ISSUE TITLE
People plug-in effects startup of other plug-ins

### ISSUE THREAD

**Issue by mattangelofdeth** [PeteLawrence/homebridge-people#71]
Hi there,
I appear to be having a small issue with the people plugin
When loaded in conjunction with the homebridge-cbius plugin, the homebridge-cbus plugin ceases to work
People loads fine
When the people config is removed, the cbus plugin appears to load correctly without issue

Any ideas to what may be the problem?

Config is as follows:

  {
  	"bridge": {
  		"name": "Homebridge",
  		"username": "CC:66:66:E3:CE:30",
  		"port": 51826,
  		"pin": "000-00-000"
  	},
  	"platforms": [{
  		"platform": "People",
  		"threshold": 15,
  		"anyoneSensor": true,
  		"nooneSensor": true,
  		"webhookPort": 51828,
  		"pingInterval": 10000,
  		"ignoreReEnterExitSeconds": 0,
  		"people": [{
  			"name": "Person 1",
  			"target": "192.168.1.211",
  			"threshold": 15,
  			"pingInterval": 10000,
  			"ignoreReEnterExitSeconds": 0
  		}, {
  			"name": "Person 2",
  			"target": "192.168.1.215",
  			"threshold": 15,
  			"pingInterval": 10000,
  			"ignoreReEnterExitSeconds": 0
  		}, {
  			"platform": "Hue",
  			"name": "Hue",
  			"host": "192.168.1.62",
  			"users": {
  				"000000000000": "yfghfdfuiWxr9y2isxBXpiudqIUy9M8Wm0"
  			},
  			"sensors": false,
  			"excludeSensorTypes": [],
  			"lowBattery": 25,
  			"lights": true,
  			"philipsLights": true,
  			"ct": false,
  			"groups": true,
  			"group0": false,
  			"rooms": false,
  			"schedules": false,
  			"rules": false,
  			"heartrate": 5,
  			"waitTimeUpdate": 20,
  			"timeout": 5,
  			"parallelRequests": 10,
  			"waitTimeResend": 300,
  			"waitTimeSwitch": 100
  		}, {
  			"platform": "homebridge-cbus.CBus",
  			"name": "CBus",
  			"client_ip_address": "192.168.1.*",
  			"client_controlport": 20023,
  			"client_cbusname": "PROJ",
  			"client_network": 253,
  			"client_application": 56,
  			"client_debug": true,
  			"accessories": [{
  				"type": "dimmer",
  				"id": 55,
  				"name": "Light Above Bed"
  			}, {
  				"type": "light",
  				"id": 8,
  				"name": "Walk In Robe"
  			}, {
  				"type": "switch",
  				"id": 63,
  				"name": "Pool Water Feature",
  				"activeDuration": "30 min"
  			}, {
  				"type": "switch",
  				"id": 83,
  				"name": "Front Gate",
  				"activeDuration": "5 sec"
  			}, {
  				"type": "light",
  				"id": 13,
  				"name": "Garage Light",
  				"activeDuration": "15 min"
  			}, {
  				"type": "light",
  				"id": 82,
  				"name": "Front Garden",
  				"activeDuration": "180 min"
  			}, {
  				"type": "dimmer",
  				"id": 1,
  				"name": "Gallery",
  				"enabled": true
  			}, {
  				"type": "unknown",
  				"id": 2,
  				"name": "Group 2",
  				"enabled": false
  			}, {
  				"type": "light",
  				"id": 3,
  				"name": "Ken Duncan Light",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 4,
  				"name": "Ensuite Shower Light",
  				"enabled": true,
  				"activeDuration": "15 min"
  			}, {
  				"type": "light",
  				"id": 5,
  				"name": "Ensuite Light",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 6,
  				"name": "Ensuite Extractor Fan",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 7,
  				"name": "Ensuite Heat Lamp",
  				"enabled": true,
  				"activeDuration": "30 min"
  			}, {
  				"type": "fan",
  				"id": 9,
  				"name": "Ensuite Toilet Fan",
  				"enabled": true,
  				"activeDuration": "10min"
  			}, {
  				"type": "dimmer",
  				"id": 10,
  				"name": "Ensuite Toilet light",
  				"rampDuration": "5 min",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 11,
  				"name": "Portico Light",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 12,
  				"name": "Front Wall Lights",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 14,
  				"name": "Side Flood Light",
  				"enabled": true,
  				"activeDuration": "10 min"
  			}, {
  				"type": "switch",
  				"id": 15,
  				"name": "Air Conditioning",
  				"enabled": true,
  				"activeDuration": "30 min"
  			}, {
  				"type": "light",
  				"id": 16,
  				"name": "Comms Room Light",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 17,
  				"name": "Comms Room Fan",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 18,
  				"name": "Comms Room Fluro Light",
  				"enabled": true
  			}, {
  				"type": "unknown",
  				"id": 19,
  				"name": "Group 19",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"id": 20,
  				"name": "Group 20",
  				"enabled": false
  			}, {
  				"type": "light",
  				"id": 21,
  				"name": "Rear Flood Light",
  				"enabled": true,
  				"activeDuration": "15 mins"
  			}, {
  				"type": "light",
  				"id": 22,
  				"name": "Meter Box Light",
  				"enabled": true,
  				"activeDuration": "10 min"
  			}, {
  				"type": "light",
  				"id": 25,
  				"name": "Millenium Photo",
  				"enabled": true,
  				"activeDuration": "2 hrs"
  			}, {
  				"type": "light",
  				"id": 27,
  				"name": "Laundry Light",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 28,
  				"name": "Outside Laundry Light",
  				"enabled": true,
  				"activeDuration": "10 mins"
  			}, {
  				"type": "dimmer",
  				"id": 29,
  				"name": "Main Bathroom Vanity",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 30,
  				"name": "Main Bathroom Centre Light",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 31,
  				"name": "Main Bathroom Fan",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 32,
  				"name": "Main Bathroom Heat Lamps",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 33,
  				"name": "Kitchen Splash Back",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 34,
  				"name": "Pantry Light",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 35,
  				"name": "Rumpus Rear Lights",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 36,
  				"name": "Rumpus Front Lights",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 37,
  				"name": "Office Light",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 38,
  				"name": "Office Fan",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 39,
  				"name": "Guest Room Lights",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 40,
  				"name": "Guest Room Fan",
  				"enabled": false
  			}, {
  				"type": "dimmer",
  				"id": 41,
  				"name": "Alfresco Lights",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 42,
  				"name": "Alfresco Fan",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 43,
  				"name": "Family Room Light",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 44,
  				"name": "Main Bathroom Lights",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 45,
  				"name": "Study Fan",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 46,
  				"name": "Study Light",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 47,
  				"name": "Kitchen Bench Lights",
  				"enabled": true,
  				"activeDuration": "2 hrs"
  			}, {
  				"type": "dimmer",
  				"id": 48,
  				"name": "Meal Lights",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 49,
  				"name": "Dining Room Light Centre",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 50,
  				"name": "Dining Room Lights",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 51,
  				"name": "Lounge Lights",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 52,
  				"name": "Ensuite vanity",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 53,
  				"name": "Ensuite Spa Light",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 54,
  				"name": "Bedroom Hallway",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 56,
  				"name": "Bedroom Down Lights",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 57,
  				"name": "Bedroom",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 58,
  				"name": "Front Entry Lights",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 59,
  				"name": "Dining hallway",
  				"enabled": true
  			}, {
  				"type": "switch",
  				"id": 60,
  				"name": "A/C virtual control",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"id": 61,
  				"name": "Temperature Set point",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"id": 62,
  				"name": "Group 62",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"id": 65,
  				"name": "Group 65",
  				"enabled": false
  			}, {
  				"type": "light",
  				"id": 66,
  				"name": "Pool Lights",
  				"enabled": true
  			}, {
  				"type": "light",
  				"id": 67,
  				"name": "Backyard Lights",
  				"enabled": true
  			}, {
  				"type": "switch",
  				"id": 68,
  				"name": "Pool Filter",
  				"enabled": true
  			}, {
  				"type": "switch",
  				"id": 69,
  				"name": "Watering Schedules Enable",
  				"enabled": false
  			}, {
  				"type": "dimmer",
  				"id": 70,
  				"name": "Barbeque",
  				"enabled": true
  			}, {
  				"type": "fan",
  				"id": 71,
  				"name": "Pergola Fan",
  				"enabled": true
  			}, {
  				"type": "dimmer",
  				"id": 72,
  				"name": "Pergola Light",
  				"enabled": true
  			}, {
  				"type": "switch",
  				"id": 73,
  				"name": "Outside Gas Heater",
  				"activeDuration": "120 min",
  				"enabled": true
  			}, {
  				"type": "switch",
  				"id": 75,
  				"name": "Pool Top up sensor",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"id": 76,
  				"name": "Group 76",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"id": 77,
  				"name": "Group 77",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"id": 78,
  				"name": "Group 78",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"id": 79,
  				"name": "Watering Moisture sensor",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"id": 80,
  				"name": "Pool Top up Solonoide",
  				"enabled": false
  			}, {
  				"type": "light",
  				"id": 81,
  				"name": "Front Fence Lights",
  				"enabled": true
  			}, {
  				"type": "switch",
  				"id": 86,
  				"name": "Garage Door",
  				"enabled": true,
  				"activeDuration": "5 sec"
  			}, {
  				"type": "unknown",
  				"id": 135,
  				"name": "Group 135",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"application": 113,
  				"id": 0,
  				"name": "Rear Garden Irrigation",
  				"enabled": true,
  				"activeDuration": "6 min"
  			}, {
  				"type": "switch",
  				"application": 113,
  				"id": 1,
  				"name": "Rear lawn Irrigation",
  				"enabled": true,
  				"activeDuration": "6 min"
  			}, {
  				"type": "switch",
  				"application": 113,
  				"id": 2,
  				"name": "Watering Reset",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"application": 113,
  				"id": 3,
  				"name": "Auto Watering Trigger",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"application": 113,
  				"id": 4,
  				"name": "Manual Watering Trigger",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"application": 113,
  				"id": 5,
  				"name": "Lawn Bypass",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"application": 113,
  				"id": 6,
  				"name": "Front Right Garden Irrigation",
  				"enabled": true,
  				"activeDuration": "6 min"
  			}, {
  				"type": "switch",
  				"application": 113,
  				"id": 7,
  				"name": "Front Left Garden Irrigation",
  				"enabled": true,
  				"activeDuration": "6 min"
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 1,
  				"name": "[CG01] Y (heat/cool)",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 2,
  				"name": "[CG01] Open",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 3,
  				"name": "[CG01] G (cool fan)",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 4,
  				"name": "[CG01] B (heat activation)",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 5,
  				"name": "[CG01] Y (cool)",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 6,
  				"name": "[CG01] Close",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 7,
  				"name": "[CG01] G1 (fan speed 1)",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 8,
  				"name": "[CG01] G2 (fan speed 2)",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 9,
  				"name": "Comms Room Temp Activation",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 20,
  				"name": "[CG01] Damper Zone 1",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 21,
  				"name": "[CG01] Damper Zone 2",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 22,
  				"name": "[CG01] Damper Zone 3",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 115,
  				"id": 23,
  				"name": "[CG01] Damper Zone 4",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 172,
  				"id": 1,
  				"name": "Comms Room Temp",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 202,
  				"id": 0,
  				"name": "BAthroom Trigger",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 202,
  				"id": 1,
  				"name": "Watering Zone Trigger",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 202,
  				"id": 2,
  				"name": "Outside lights Trigger",
  				"enabled": false
  			}, {
  				"type": "fan",
  				"application": 202,
  				"id": 3,
  				"name": "bed 1 fan trigger",
  				"enabled": false
  			}, {
  				"type": "fan",
  				"application": 202,
  				"id": 4,
  				"name": "study fan trigger",
  				"enabled": false
  			}, {
  				"type": "fan",
  				"application": 202,
  				"id": 5,
  				"name": "bed 3 fan trigger",
  				"enabled": false
  			}, {
  				"type": "fan",
  				"application": 202,
  				"id": 6,
  				"name": "Pergola fan trigger",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 202,
  				"id": 8,
  				"name": "Front Left Watering Trigger",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 202,
  				"id": 9,
  				"name": "Front Right Watering",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 202,
  				"id": 10,
  				"name": "All Off Trigger",
  				"enabled": false
  			}, {
  				"type": "fan",
  				"application": 202,
  				"id": 12,
  				"name": "Guest Room Fan",
  				"enabled": true
  			}, {
  				"type": "switch",
  				"application": 203,
  				"id": 0,
  				"name": "Auto Filtering",
  				"enabled": false
  			}, {
  				"type": "switch",
  				"application": 203,
  				"id": 1,
  				"name": "A/C Schedule Enable",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 203,
  				"id": 17,
  				"name": "Group 17",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 203,
  				"id": 32,
  				"name": "Enable Network Variable 32",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 203,
  				"id": 33,
  				"name": "Enable Network Variable 33",
  				"enabled": false
  			}, {
  				"type": "unknown",
  				"application": 203,
  				"id": 34,
  				"name": "Enable Network Variable 34",
  				"enabled": false

  			}]
  		}],
  		"accessories": [{
  			"accessory": "Weather",
  			"apikey": "--",
  			"locationById": "7281823",
  			"name": "OpenWeatherMap Temperature"
  		}]
  	}]
  }

**Comment by benzman81** [comment]
Before the Hue Platform the brackets must look like "}]}, {" instead of "}, {".

**Comment by mattangelofdeth** [comment]
THANKYOU!!!!!!!! REALLY appreciate your help :)
