### ISSUE TITLE
Mac adress?

### ISSUE THREAD

**Issue by matzZz** [PeteLawrence/homebridge-people#73]
Works mac adress as target as well?

**Comment by SkyJohn** [comment]
I don't think it would work, each device would need to connect to your homebridge host for it to have the record of the MAC address.

**Comment by PeteLawrence** [comment]
I can't see this working because as @SkyJohn says, the device would need to have communicated with the homebridge server in order for an ARP record to exist.

**Comment by GatoPharaoh** [comment]
@matzZz check [Homebridge People Plus](https://github.com/Glavin001/homebridge-people-plus)
