### ISSUE TITLE
Locative replacement?

### ISSUE THREAD

**Issue by ToddGreenfield** [PeteLawrence/homebridge-people#75]
Hey all, so Locative https://blog.locative.io/bye-everyone-df01871fe949 is now gone as of mid-May. I was using this service for geo tracking in conjunction with the people plugin. What other location-aware services that can trigger a web hook are you all using with success?

**Comment by JonSilver** [comment]
I'm still using Locative, and will continue to do so for as long as it works on iOS. It still calls webhooks, and it's still the most light-weight and reliable thing available. The only difference now is that if you want to maintain a geofence entry/exit history, you have to do it yourself using something like node-red to provide the REST endpoints. Using homebridge-people to provide the endpoint still works just the same way it always did.

**Comment by ToddGreenfield** [comment]
Weird. I am unable to get the hooks from the Locative app on my phone. The plugin still works and I can manually hit the correct URL in a browser but doesn't work from my phone. The syslog shows something was received but not a correct sensor. Same URL works though... more troubleshooting I guess-

**Comment by GatoPharaoh** [comment]
If automation is a possibility, install `homebridge-cmdswitch2`, use the webhook urls as on and off commands, go to Home.app and tell it to turn the switch on when at home and off when away from home.
