### ISSUE TITLE
Option to ignore exits and immediate reenters? iBeacon has short disconnects

### ISSUE THREAD

**Issue by tonwelle** [PeteLawrence/homebridge-people#81]
I have successfully installed a virtual iBeacon on my Pi and use it with webhooks on homebridge people.
The response is really fast and accurate with the geofency app, but the iBeacon sometimes disconnects just for some seconds or one minute when I'm moving through my home and so triggers an immediate exit and reenter which then turns off lights and home stereo.
An option to have the plugin wait for an immediate reenter within a configurable amount of time when using webhooks would solve this and would be fantastic. ;)
The thresholdoption, for example could be made optionally available when using webhooks.

**Comment by benzman81** [comment]
Hi, this is why the option ignoreReEnterExitSeconds was introduced ;-)

**Comment by tonwelle** [comment]
But it does not seem to work for me here.  
When the Webhooks fires, it immediately sets my state to away, not waiting for the configured 60 seconds for a reenter to occur.

**Comment by benzman81** [comment]
Thats weird. Can you see anything in the logs?

**Comment by tonwelle** [comment]
Ok, it’s working now. As always if you post an issue it starts working right away. ;-)
I think I made a config error in having the reenterexitseconds thing not under people but in the general config block.

Thanks a lot anyway. :-)
